"""add users

Revision ID: a0bcee80082a
Revises: 7e6de6928c55
Create Date: 2019-04-08 23:05:42.388584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bcee80082a'
down_revision = '7e6de6928c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('api_key', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tweets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
